# Generated by Django 4.0.2 on 2022-03-05 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('music_id', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=255)),
                ('add_at', models.DateField(default=datetime.datetime(2022, 3, 5, 2, 42, 33, 512229, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=datetime.datetime(2022, 3, 5, 2, 42, 33, 512945, tzinfo=utc))),
                ('musics', models.ManyToManyField(to='music.MusicModel')),
            ],
        ),
    ]
