# Generated by Django 4.0.2 on 2022-03-05 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicmodel',
            name='video_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 18, 3, 39, 286536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='music_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 18, 3, 39, 287477, tzinfo=utc)),
        ),
    ]
