# Generated by Django 4.0.2 on 2022-03-05 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicmodel_image_url_musicmodel_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 18, 5, 4, 591361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='music_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 18, 5, 4, 592414, tzinfo=utc)),
        ),
    ]
