# Generated by Django 4.0.2 on 2022-03-05 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_musicmodel_add_at_alter_musicmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 18, 6, 16, 834348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 18, 6, 16, 835803, tzinfo=utc)),
        ),
    ]
