# Generated by Django 4.0.2 on 2022-03-14 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 3, 29, 45, 416598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 3, 29, 45, 417855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='musics',
            field=models.ManyToManyField(blank=True, null=True, to='music.MusicModel'),
        ),
    ]
