# Generated by Django 4.0.2 on 2022-03-14 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_musicmodel_add_at_alter_musicmodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 16, 51, 47, 180900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 16, 51, 47, 181877, tzinfo=utc)),
        ),
    ]
