# Generated by Django 4.0.2 on 2022-03-14 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_playlistmodel_privacy_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 20, 11, 30, 734767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 20, 11, 30, 735734, tzinfo=utc)),
        ),
    ]
