# Generated by Django 4.0.2 on 2022-03-15 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlistmodel_password_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 15, 18, 50, 11, 140892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 15, 18, 50, 11, 142221, tzinfo=utc)),
        ),
    ]
