# Generated by Django 4.0.2 on 2022-03-22 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_playlistmodel_thumb_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 1, 52, 20, 531292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 1, 52, 20, 532404, tzinfo=utc)),
        ),
    ]
