# Generated by Django 4.0.2 on 2022-03-24 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_playlistmodel_likes_playlistmodel_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 17, 46, 23, 590196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 17, 46, 23, 591253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
