# Generated by Django 4.0.2 on 2022-04-09 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 4, 9, 22, 59, 51, 291528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 4, 9, 22, 59, 51, 292985, tzinfo=utc)),
        ),
    ]
