# Generated by Django 4.0.2 on 2022-04-10 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_playlistmodel_thumb_url_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 17, 9, 42, 699729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 17, 9, 42, 701061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumb/'),
        ),
    ]
