# Generated by Django 4.0.4 on 2022-05-05 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 21, 56, 35, 679666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 21, 56, 35, 680763, tzinfo=utc)),
        ),
    ]
