# Generated by Django 4.0.4 on 2022-06-21 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_musicmodel_add_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='add_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 1, 12, 18, 654707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 1, 12, 18, 655671, tzinfo=utc)),
        ),
    ]
